field: 9daa8206-1472-49bf-9d97-46d263d29017 # Consulting services
fieldLayouts:
  27f31cfa-5264-41a5-aaf9-a53480c6e045:
    tabs:
      -
        elements:
          -
            fieldUid: 0e91a37e-fd03-4d56-8c2a-b7cb5f496b22 # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: aeecf68b-9fdf-4206-8a70-ec2e439feedf # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cc1a6f2d-b95e-4272-81a2-50e6a2e643d7 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f368ef18-bad7-43ac-b7be-1637624a6867 # Page
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8b55667f-e342-49ce-9193-039e14f7e8bf # Button text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e8d4a6c2-eafd-49d7-ba61-fdbb345e53d6 # Hide on mobile
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0e91a37e-fd03-4d56-8c2a-b7cb5f496b22: # Heading
    columnSuffix: zscluvmo
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8b55667f-e342-49ce-9193-039e14f7e8bf: # Button text
    columnSuffix: skyiiebv
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  aeecf68b-9fdf-4206-8a70-ec2e439feedf: # Text
    columnSuffix: hbmbmgim
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cc1a6f2d-b95e-4272-81a2-50e6a2e643d7: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - svg
      defaultUploadLocationSource: 'volume:e63ebaa0-2a25-41c3-8a67-4f34be027d55' # Global
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:e63ebaa0-2a25-41c3-8a67-4f34be027d55' # Global
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:09e85ea6-be6e-4f00-8e26-ff14769b4d86' # Common
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e8d4a6c2-eafd-49d7-ba61-fdbb345e53d6: # Hide on mobile
    columnSuffix: hhxmcwpt
    contentColumnType: boolean
    fieldGroup: null
    handle: hideOnMobile
    instructions: ''
    name: 'Hide on mobile'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  f368ef18-bad7-43ac-b7be-1637624a6867: # Page
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: page
    instructions: ''
    name: Page
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: service
name: Service
sortOrder: 1
