columnSuffix: null
contentColumnType: string
fieldGroup: e9ed4033-f150-4073-8ef1-cbcf99628593 # Contact
handle: branches
instructions: ''
name: Branches
searchable: false
settings:
  contentTable: '{{%matrixcontent_branches}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
