columnSuffix: null
contentColumnType: string
fieldGroup: d0956545-0242-4f9c-8ede-a539c2cd6346 # Home
handle: documentationStamp
instructions: ''
name: 'Documentation stamp'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - svg
  defaultUploadLocationSource: 'volume:e63ebaa0-2a25-41c3-8a67-4f34be027d55' # Global
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:e63ebaa0-2a25-41c3-8a67-4f34be027d55' # Global
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:09e85ea6-be6e-4f00-8e26-ff14769b4d86' # Common
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
