columnSuffix: null
contentColumnType: string
fieldGroup: d0956545-0242-4f9c-8ede-a539c2cd6346 # Home
handle: documentationItems
instructions: ''
name: 'Documentation items'
searchable: false
settings:
  contentTable: '{{%matrixcontent_documentationitems}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
