columnSuffix: null
contentColumnType: string
fieldGroup: 710dd5cc-4bd6-406b-97c4-cac686f67c67 # Global Settings 
handle: headerLogo
instructions: ''
name: 'Header logo'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - svg
  defaultUploadLocationSource: 'volume:e63ebaa0-2a25-41c3-8a67-4f34be027d55' # Global
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:e63ebaa0-2a25-41c3-8a67-4f34be027d55' # Global
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:e63ebaa0-2a25-41c3-8a67-4f34be027d55' # Global
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
