columnSuffix: null
contentColumnType: string
fieldGroup: d0956545-0242-4f9c-8ede-a539c2cd6346 # Home
handle: heroButtonPage
instructions: ''
name: 'Hero button page'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
