columnSuffix: ontwaxns
contentColumnType: text
fieldGroup: d0956545-0242-4f9c-8ede-a539c2cd6346 # Home
handle: heroText
instructions: ''
name: 'Hero text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
