columnSuffix: null
contentColumnType: string
fieldGroup: 82acd991-4cf7-40e9-a10d-45c8fb2c5b66 # Page Contact Widget
handle: pageContactWidgetTargetPage
instructions: ''
name: 'Page contact widget target page'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
