columnSuffix: null
contentColumnType: string
fieldGroup: 2877181c-2bb7-487b-9a3d-70e2e0484f92 # Page
handle: pageHeroImage
instructions: ''
name: 'Hero image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:e63ebaa0-2a25-41c3-8a67-4f34be027d55' # Global
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:e63ebaa0-2a25-41c3-8a67-4f34be027d55' # Global
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:09e85ea6-be6e-4f00-8e26-ff14769b4d86' # Common
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
