columnSuffix: null
contentColumnType: string
fieldGroup: d0956545-0242-4f9c-8ede-a539c2cd6346 # Home
handle: products
instructions: ''
name: Products
searchable: false
settings:
  contentTable: '{{%matrixcontent_products}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
