fieldLayouts:
  f69a8c5c-590c-4fbc-bc82-15bc25db24a6:
    tabs:
      -
        elements:
          -
            fieldUid: 45c341e1-4a75-4067-9ccd-1157b25cf8e2 # Page contact widget icons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b29454fe-c06c-45e5-b9fa-853741194abd # Page contact widget button text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 084a2a4b-89ab-4b71-a82b-7b097b57b5ac # Page contact widget target page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
handle: pageContactWidget
name: 'Page Contact Widget'
sortOrder: 2
