defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  fe16f9ac-2784-4573-a588-52d30e51d3c0: # Inorms RU
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
